### ISSUE TITLE
Download archive data

### ISSUE THREAD

**Issue by SergioG-M** [guidocioni/icon_forecasts#2]
Is there any way to download the historical archive of forecasts? Your code can download the most updated forecast, but is it possible to also download past forecasts?

**Comment by guidocioni** [comment]
Archived forecasts are not stored on opendata, you have to request access to PAMORE: https://www.dwd.de/DE/leistungen/pamore/pamore.html

**Comment by SergioG-M** [comment]
Thanks for the info
